version: '3'

volumes:
  mysql_data:
      driver: local
networks:
  ms-users:
    driver: bridge
  keycloak-local:
    driver: bridge

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      networks:
        - keycloak-local
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      command: ["-Djboss.http.port=8100"]
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      ports:
        - 8100:8100
      depends_on:
        - mysql
      networks:
        - ms-users
        - keycloak-local