server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ms-users
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]

keycloak:
  url: ${KEYCLOAK_URL}
  auth-server-url: ${keycloak.url}/auth
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}

app:
  keycloak:
    client-id: ${keycloak.resource}
    client-secret: ${KEYCLOAK_CREDENTIALS_SECRET}
    login.url: ${keycloak.url}/auth/realms/demo/protocol/openid-connect/token
