
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: ms-users
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]

keycloak:
  url: http://localhost:8080/auth
  realm: myrealm
  resource: myclient
  credentials:
    secret: mysecret
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}

