version: '3'
services:
  ms-users:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-users:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ec2-34-204-18-22.compute-1.amazonaws.com:3306/users
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_URL: http://ec2-18-215-159-36.compute-1.amazonaws.com:8080
      KEYCLOAK_RESOURCE: user-app
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    networks:
      - ms-users
networks:
  ms-users:
    driver: bridge
