version: '3'
services:
  ms-users:
    image: ${IMAGE}
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_RESOURCE: user-app
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      MS_ACCOUNTS_DNS: http://ms-accounts:8082
      MS_MAILS_DNS: http://ms-mails:8084
    networks:
      - podnet
networks:
  podnet:
    external: true