version: '3'
services:
  ms-users:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-users:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://users_db:3306/users
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_URL: http://keycloak:8081/auth
      KEYCLOAK_REALM: myrealm
      KEYCLOAK_RESOURCE: myclient
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ms-users
    depends_on:
      - users_db
      - keycloak
networks:
  ms-users:
    driver: bridge
