version: '3'
services:
  ms-accounts:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: ${IMAGE}
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      #  g5network:
  #    - g5network
#    depends_on:
#      - users_db
#      - keycloak
networks:
  g5network:

