version: '3'
services:
  ms-mails:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: ${IMAGE}
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - podnet

networks:
  podnet:
    external: true


