version: '3'
services:
  ms-users:
    image: ${IMAGE}
    ports:
      - "80:8083"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_RESOURCE: user-app
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
networks:
  g5network:

