version: '3'
services:
  gateway:
    image: ${IMAGE}
    ports:
      - "80:8083"
    environment:
      MS_USERS_DNS: http://ms-users:8081
      MS_ACCOUNTS_DNS: http://ms-accounts:8082
    networks:
      - podnet
networks:
  podnet:
    external: true