version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: gateway:1.0
    ports:
      - "80:8083"
    environment:
      MS_USERS_DNS: ms-users
      MS_ACCOUNTS_DNS: ms-accounts
    networks:
      - ms-users
    depends_on:
      - ms-users
      - ms-accounts
networks:
  ms-users:
    driver: bridge
