version: '3'
services:
  ms-accounts:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-users:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://users_db:3306/accounts
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ms-users
    depends_on:
      - users_db
networks:
  ms-users:
    driver: bridge
