version: '3'
services:
  ms-accounts:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-accounts:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ec2-34-204-18-22.compute-1.amazonaws.com:3306/accounts
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ms-users
networks:
  ms-users:
    driver: bridge
